import type { Call, Deal, Draft, Integration, Task } from "./types";
export const deals: Deal[] = [
 {id:"deal_techflow",account:"TechFlow",name:"Enterprise Expansion",stage:"Discovery",value:120000,due:"Today, 4 PM",owner:"Demo Rep",primaryContact:"Nina Patel",budget:"$100k – $150k",timeline:"Q1 2027",decisionMaker:"Nina Patel",competitors:"None known"},
 {id:"deal_acme",account:"Acme Corp",name:"Q3 Renewal",stage:"Proposal",value:45000,due:"Oct 24",owner:"Demo Rep",primaryContact:"Sarah Jenkins",budget:"$150k – $200k",timeline:"Q1 2024",decisionMaker:"Sarah Jenkins",competitors:"Logisync, Oracle"},
 {id:"deal_stark",account:"Stark Ind.",name:"Stark Ind. Pilot",stage:"Negotiation",value:250000,due:"Pending",owner:"Demo Rep",primaryContact:"Tony Stark",budget:"Not specified",timeline:"Not specified",decisionMaker:"Tony Stark",competitors:"Not specified"},
 {id:"deal_global",account:"GlobalNet",name:"GlobalNet Integration",stage:"Closed Won",value:85500,due:"Oct 20",owner:"Demo Rep",primaryContact:"Grace Ng",budget:"$85,500",timeline:"Closed",decisionMaker:"Grace Ng",competitors:"None"}
];
export const drafts: Draft[] = [{id:"draft_acme",callId:"call_acme",to:"sarah.j@acmecorp.com",subject:"Following up: Gravity + Acme Corp Ops Efficiency",status:"awaiting_approval",gmailDraftId:"demo_gmail_draft",body:`Hi Sarah,\n\nGreat speaking with you and the team today. It’s clear that reducing the 12% manual data entry error rate in your fulfillment centers is a top priority for Q1.\n\nAs promised, I’ve attached our technical documentation regarding the SAP integration to address your team’s architecture questions. We are confident we can deploy without disrupting your peak season operations.\n\nI will follow up shortly with a customized ROI calculator based on the $1.2M shrinkage figure we discussed.\n\nAre you and your lead architect available next Tuesday at 10 AM PST for a technical deep dive?\n\nBest,\nDemo Rep`}];
export const calls: Call[] = [{id:"call_acme",title:"Acme Corp Initial Discovery",date:"Oct 24, 2023 - 10:00 AM PST",duration:"45m 12s",source:"Zoom",dealId:"deal_acme",draftId:"draft_acme",status:"processed",transcriptUrl:"#demo-transcript",summary:"The Acme Corp team, led by Sarah Jenkins, VP Ops, is primarily concerned with reducing manual data entry errors across their fulfillment centers. They are currently using a legacy system that causes a 12% error rate, translating to roughly $1.2M in annual shrinkage. They expressed strong interest in our automated reconciliation module, provided it can integrate seamlessly with their existing SAP backend.",objections:["Implementation time might disrupt peak season operations.","Concerned about data residency requirements for their EU warehouses.","Pushback on per-user pricing model vs flat site license."],commitments:["Provide SAP integration technical documentation by Friday.","Schedule a deep-dive demo with their lead architect next week.","Send over a customized ROI calculator based on their $1.2M shrinkage figure."]}];
export const tasks: Task[] = [{id:"task_1",title:"Send updated pricing proposal for Q3",source:"Acme Corp Sync",due:"Due Today",owner:"Rep",completed:false},{id:"task_2",title:"Provide technical specs for API integration",source:"Tech Review",due:"Due Oct 14",owner:"Client",completed:false},{id:"task_3",title:"Schedule follow-up meeting with procurement",source:"Intro Call",due:"Due Oct 10",owner:"Rep",completed:true}];
export const integrations: Integration[] = ["Gmail","Google Calendar","Zoom","Google Drive","Slack","HubSpot","Google Sheets"].map(provider=>({provider:provider as Integration["provider"],connected:["Gmail","Google Calendar","Zoom"].includes(provider)}));
